version: '3.8'

services:
  app:
    image: 'titan-app'
    build:
      context: .

    container_name: 'app'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/titan'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'titan'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
    ports:
      - '9000:9000'

  db:
    image: 'postgres:latest'
    container_name: 'db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: titan
      POSTGRES_DB: titan
      POSTGRES_USER: root
