version: '3.8'

services:
  db:
    image: postgres
    container_name: titan
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: titan
      POSTGRES_DB: titan
      POSTGRES_USER: root
